name: Scheduled Python Script

on:
  schedule:
    - cron: '0 */1 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run scraper.py
      run: |
        python scraper.py
